### ISSUE TITLE
In Turkish, certain characters are bolded when the font weight is 300

### ISSUE THREAD

**Issue by svanherk** [Brightspace/valence-ui-typography#47]
We use this repo for our Class Engagement FRA, and when the page is displayed in Turkish we are finding that the characters ğ and ş don't seem to support a font-weight of 300.  The result looks like this:

![image](https://cloud.githubusercontent.com/assets/13419300/14360000/245c7f36-fcc2-11e5-95ec-9842ce9bf2bd.png)

For the search bar, we are using valence-ui-input.

**Comment by dlockhart** [comment]
Neat! Those glyphs appear to be missing from the Lato font specification, as using them on [Google Fonts](https://www.google.com/fonts#ChoosePlace:select/Collection:Lato) in the preview has the same results.

**Comment by dlockhart** [comment]
Update: seems like maybe Google is hosting an older version of the Lato font. Suggest we download and test out the latest version of the font from here:
http://www.latofonts.com/lato-free-fonts/#download
